# Generated by Django 3.1.4 on 2021-01-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210114_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('E', 'Electronics'), ('H', 'Home'), ('F', 'Fashion'), ('T', 'Toys'), ('A', 'Automobiles'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
