# Generated by Django 3.1.4 on 2021-01-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210112_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_comments',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='user_listing',
            new_name='user',
        ),
    ]
