# Generated by Django 3.1.4 on 2021-01-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('N', 'None'), ('E', 'Electronics'), ('H', 'Home'), ('F', 'Fashion'), ('T', 'Toys'), ('A', 'Automobiles'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
