# Generated by Django 3.1.4 on 2021-01-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210112_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user_bids',
            new_name='user',
        ),
    ]
