# Generated by Django 3.1.4 on 2021-01-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210115_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='listing',
            name='comment_title',
            field=models.ManyToManyField(related_name='listing_comment_title', to='auctions.Comment'),
        ),
    ]
