# Generated by Django 3.1.4 on 2021-01-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210115_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='comment_title',
        ),
    ]
