# Generated by Django 3.1.4 on 2021-01-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210118_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='user_watchlist', to='auctions.Watchlist'),
        ),
    ]
