# Generated by Django 3.1.4 on 2021-01-18 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Watchlist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to='auctions.watchlist'),
        ),
    ]
