# Generated by Django 3.1.4 on 2021-01-19 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Watchlist',
            new_name='watchlist',
        ),
    ]
